# ----------------------------
# General project configuration
# ----------------------------
root = "FileName"
mode = "official"
ignore_vendor = false
scan_root_only = false
debug = false

# ----------------------------
# Paths
# ----------------------------
vendor_libs_dir = "${HOME}/Workspace/Libs/SL_Library/"
programs_dir = "${HOME}/Workspace/Libs/Programs"

libs_dirs = ["${HOME}/Workspace/Libs/1/", "${HOME}/Workspace/Libs/2/"]
